### ISSUE TITLE
Bug report: LinkConverter not in SysPreferences>Notifications

### ISSUE THREAD

**Issue by MKlafke** [lumibit/linkconverter#6]
**Describe the bug**
No notifications coming up for LinkConverter (v1.2.1-52n) after installation if copying a link. Under settings>options>notifications were "on". Checked in system preferences>Notifications&Focus: LinkConverter wasn't listed. 
To solve the bug: 
Reopen settings on LinkConverter settings>options>notifications and switched notifications off and on again. Logged out and started system preferences again. LinkConverter was in List now and I was able to enable notifications.

**To Reproduce**
1. Install LinkConverter
2. Check notifications in LinkConverter Settings
3. Check system preferences

**Expected behavior**
After installing LinkConverter get asked if I want to get notifications or notifications are on per default, if possible

**Screenshots**

**MacOS (please complete the following information):**
 - MacOS version: 12.3.
 - LinkConverter Version: v1.2.1.-52n

**Additional context**

**Comment by flymg** [comment]
closed in 1.3.0
